# Generated by Django 5.0.4 on 2026-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('game', models.CharField(choices=[('gta', 'GTA'), ('minecraft', 'Minecraft'), ('wow', 'WorldOfWarcraft'), ('cs', 'Counter')], max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'inActive')], max_length=64)),
                ('cpu_cores', models.PositiveIntegerField()),
                ('RAM', models.PositiveIntegerField()),
                ('traffic', models.PositiveIntegerField()),
                ('price_per_month', models.PositiveIntegerField()),
            ],
        ),
    ]
